name: Server Workflow
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]
jobs:
 build:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       node-version: [14.x, 16.x, 18.x, 20.x]
   steps:
     - uses: actions/checkout@v3
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v3
       with:
         node-version: ${{ matrix.node-version }}
     - run: cd backend && npm install
     - run: npm run dev --if-present

name: Client Workflow
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]
jobs:
 build:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       node-version: [14.x, 16.x, 18.x, 20.x]
   steps:
     - uses: actions/checkout@v3
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v3
       with:
         node-version: ${{ matrix.node-version }}
     - run: cd frontend && npm install
     - run: npm start --if-present